CREATE TABLE DEPARTMENT_TBL (
    DEPT_ID CHAR (2),
    DEPT_TITLE VARCHAR2 (35),
    LOCATION_ID CHAR(2)
);
-- 데이터타입 조회
DESC DEPARTMENT_TBL; 

INSERT INTO DEPARTMENT_TBL VALUES('D1', '인사관리부', 'L1');
INSERT INTO DEPARTMENT_TBL VALUES('D2', '회계관리부', 'L1');
INSERT INTO DEPARTMENT_TBL VALUES('D3', '마케팅부', 'L1');
INSERT INTO DEPARTMENT_TBL VALUES('D4', '국내영업부', 'L1');
INSERT INTO DEPARTMENT_TBL VALUES('D5', '해외영업1부', 'L2');
INSERT INTO DEPARTMENT_TBL VALUES('D6', '해외영업2부', 'L3');
INSERT INTO DEPARTMENT_TBL VALUES('D7', '해외영업3부', 'L4');
INSERT INTO DEPARTMENT_TBL VALUES('D8', '기술지원부', 'L5');
INSERT INTO DEPARTMENT_TBL VALUES('D9', '총무부', 'L1');

-- 데이터 삭제 -> 회원탈퇴
DELETE FROM DEPARTMENT_TBL;

-- 컬럼 COMMMENT 설정
COMMENT ON COLUMN DEPARTMENT_TBL.DEPT_ID IS '부서코드';
COMMENT ON COLUMN DEPARTMENT_TBL.DEPT_TITLE IS '부서명';
COMMENT ON COLUMN DEPARTMENT_TBL.LOCATION_ID IS '지역코드';

-- 데이터조회
SELECT DEPT_ID, DEPT_TITLE, LOCATION_ID
FROM DEPARTMENT_TBL;

-- 전체조회
SELECT * FROM DEPARTMENT_TBL;

-- 컬럼전체조회
SELECT * FROM ALL_COL_COMMENTS WHERE TABLE_NAME = 'DEPARTMENT_TBL';

---------------------------------------

CREATE TABLE LOCATION_TBL (
    LOCAL_CODE CHAR (2),
    DNATIONAL_CODE CHAR (2),
    LOCAL_NAME VARCHAR2(40)
);
-- 컬럼 오타 수정 
ALTER TABLE LOCATION_TBL RENAME COLUMN DNATIONAL_CODE TO NATIONAL_CODE;

-- 전체조회
SELECT * FROM LOCATION_TBL;

INSERT INTO LOCATION_TBL VALUES('L1', 'KO', 'ASIA1');
INSERT INTO LOCATION_TBL VALUES('L2', 'JP', 'ASIA2');
INSERT INTO LOCATION_TBL VALUES('L3', 'CH', 'ASIA3');
INSERT INTO LOCATION_TBL VALUES('L4', 'US', 'AMERICA');
INSERT INTO LOCATION_TBL VALUES('L5', 'RU', 'EU');

-- 컬럼 COMMMENT 설정
COMMENT ON COLUMN LOCATION_TBL.LOCAL_CODE IS '지역코드';
COMMENT ON COLUMN LOCATION_TBL.NATIONAL_CODE IS '국가코드';
COMMENT ON COLUMN LOCATION_TBL.LOCAL_NAME IS '지역명';

-- 데이터조회
SELECT DEPT_ID, DEPT_TITLE, LOCATION_ID
FROM DEPARTMENT_TBL;

-- 전체조회
SELECT * FROM DEPARTMENT_TBL;

-- 컬럼전체조회
SELECT * FROM ALL_COL_COMMENTS WHERE TABLE_NAME = 'LOCATION_TBL';

SELECT LOCAL_CODE, DNATIONAL_CODE, LOCAL_NAME
FROM LOCATION_TBL;

-------------------------------------------------
CREATE TABLE JOB_TBL(
    JOB_CODE CHAR(2),
    JOB_NAME VARCHAR2 (35)
);

INSERT INTO JOB_TBL VALUES ('J1', '대표');
INSERT INTO JOB_TBL VALUES ('J2', '부사장');
INSERT INTO JOB_TBL VALUES ('J3', '부장');
INSERT INTO JOB_TBL VALUES ('J4', '차장');
INSERT INTO JOB_TBL VALUES ('J5', '과장');
INSERT INTO JOB_TBL VALUES ('J6', '대리');
INSERT INTO JOB_TBL VALUES ('J7', '사원');

SELECT * FROM JOB_TBL;


-- 컬럼 COMMMENT 설정
COMMENT ON COLUMN JOB_TBL.JOB_CODE IS '직급코드';
COMMENT ON COLUMN JOB_TBL.JOB_NAME IS '직급명';

-- 컬럼전체조회
SELECT * FROM ALL_COL_COMMENTS WHERE TABLE_NAME = 'LOCATION_TBL';







