CREATE TABLE STUDENT_TBL (
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);
-- 수정 -> 삭제 + 생성
-- 테이블 삭제 
DROP TABLE STUDENT_TBL;

-- TABLE에 데이터를 넣는 방법 -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('이호랑', 22, 1, '에버랜드');
-- 컬럼명 생략 가능 
INSERT INTO STUDENT_TBL VALUES('김사자', 20, 3, '아프리카');
INSERT INTO STUDENT_TBL VALUES('', 27, 4, NULL);
INSERT INTO STUDENT_TBL VALUES('최토끼', 32, 2, NULL);
INSERT INTO STUDENT_TBL VALUES('이거북', 100, 1, '하와이');

UPDATE STUDENT_TBL
SET STUDENT_AGE = 99
WHERE STUDENT_GRADE = 2;

DELETE FROM STUDENT_TBL
WHERE STUDENT_GRADE = 4;

-- 데이터 삭제 -> 회원탈퇴
DELETE FROM STUDENT_TBL;

CREATE TABLE DATATYPE_TBL (
    MOONJJA CHAR(10), 
    --알파벳 10글자, 한글 3글자
    MOONJJAYUL VARCHAR2 (100), 
    -- 알파벳100글자, 한글33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);

-- 데이터타입 조회
DESC DATATYPE_TBL; 
 
INSERT INTO DATATYPE_TBL
VALUES('문자', '문자열', 22, SYSDATE, SYSTIMESTAMP);
SELECT MOONJJA, MOONJJAYUL, SOOJJA, NALJJA, NALJJA2
FROM DATATYPE_TBL;
INSERT INTO DATATYPE_TBL
VALUES('문자2', '문자열2', 33, SYSDATE, SYSTIMESTAMP);

UPDATE DATATYPE_TBL
SET MOONJJAYUL = '오라클이 제일 쉬웠어요'
WHERE SOOJJA = 33;

DELETE FROM DATATYPE_TBL
WHERE SOOJJA = 22;

-- 데이터 조회
-- FROM -> WHERE -> SELECT
SELECT STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS
FROM STUDENT_TBL;
WHERE STUDENT_GRADE = 2;


