-- KH계정을 만들고 그 비밀번호는 KH로 해주세요
CREATE USER KH IDENTIFIED BY KH;
-- 접속이 가능하고 테이블이 생성할수 있도록 해주세요
GRANT CONNECT TO KH;
CREATE TABLE  DEPARTMENT_TBL (
    STUDENT_NAME VARCHAR(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR(100)
);
GRANT RESOURCE TO KH;





-- 사용자 계정 생성, 권한부여 및 해제
-- 비밀번호는 대소문자를 구분함
CREATE USER STUDENT IDENTIFIED BY STUDENT; 

GRANT CONNECT TO STUDENT;
-- GRANT 성공

CREATE TABLE  STUDENT_TBL (
    STUDENT_NAME VARCHAR(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR(100)
);

GRANT RESOURCE TO STUDENT;

